#! /bin/bash

# NAUTILUS_SCRIPT_SELECTED_FILE_PATHS 
#	newline-delimited paths for selected files (only if local) 
# NAUTILUS_SCRIPT_SELECTED_URIS
#	newline-delimited URIs for selected files 
#NAUTILUS_SCRIPT_CURRENT_URI
# 	current location 
#NAUTILUS_SCRIPT_WINDOW_GEOMETRY
#	position and size of current window 
#NAUTILUS_SCRIPT_SELECTED_FILE_PATHS=$(echo $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS | tr -d '\n')
#	remove newline from the end of string

#DIR=$(dirname $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS)
#FILE=$(basename $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS)
#EXTENSION="${FILE##*.}"

# Check if the fale has extension
#if [ "$EXTENSION" == "$FILE" ]; then
#    echo "File without extension"
#    FILENAME=$FILE
#else
#    echo "File has extension"
#    FILENAME="${FILE%.*}"
#fi
