#! /bin/bash



# Current path
DIR=$(pwd)


# Ask for new folder nam
FOLDER_NAME=$(zenity --entry --title="New folder name" --text=$(pwd))

#NAUTILUS_SCRIPT_SELECTED_FILE_PATHS="$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS\n"


zenity --info --text=$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS

echo $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS |
while IFS="\n" read -r line
do
  FILE=$(basename $line)
  zenity --entry --title="New folder name" --text=$line
  echo "Copying $line"
  mkdir -p $DIR/$FOLDER_NAME
  cp $line $DIR/$FOLDER_NAME/$FILE
done



exit 0






