#! /bin/bash

# newline-delimited paths for selected files (only if local) 
# NAUTILUS_SCRIPT_SELECTED_FILE_PATHS
    
# newline-delimited URIs for selected files 
# NAUTILUS_SCRIPT_SELECTED_URIS
    
# current location
# NAUTILUS_SCRIPT_CURRENT_URI

# position and size of current window 
# NAUTILUS_SCRIPT_WINDOW_GEOMETRY

#zenity --question --title="$FILENAME" --text="\
#NAUTILUS_SCRIPT_SELECTED_FILE_PATHS: $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS \n\
#NAUTILUS_SCRIPT_SELECTED_URIS: $NAUTILUS_SCRIPT_SELECTED_URIS \n\
#NAUTILUS_SCRIPT_CURRENT_URI: $NAUTILUS_SCRIPT_CURRENT_URI \n\
#NAUTILUS_SCRIPT_WINDOW_GEOMETRY: $NAUTILUS_SCRIPT_WINDOW_GEOMETRY"


SAVEIFS=$IFS
IFS=$(echo -en "\n\b")

for FILE in $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS
do 
    DIR=$(dirname $FILE)
    FILENAME=$(basename $FILE)
    EXTENSION='${$FILE##*.}'
	#zenity --info --text="File: $FILENAME"
	
	# Replace spaces with underscore
	FILE_UNERSCORE=`echo $FILENAME | tr -s ' ' | tr ' ' '_'`
	mv -i $FILENAME `echo $FILE_UNERSCORE`
	# Replace upper case to lower case
	mv -i $FILE_UNERSCORE `echo $FILE_UNERSCORE | tr 'A-Z' 'a-z'`
done


DIR=$(dirname $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS)
FILENAME=$(basename $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS)
EXTENSION='${$FILE##*.}'

# Remove newline from NAUTILUS_SCRIPT_SELECTED_FILE_PATHS
NAUTILUS_SCRIPT_SELECTED_FILE_PATHS=$(echo $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS | tr -d '\n')

# Check if the file has extension
if [ '$EXTENSION' == '$FILE' ]; then
    echo "File without extension"
    FILENAME='$FILE'
else
    echo "File has extension"
    FILENAME="${FILE%.*}"
fi


# Restore IFS
IFS=$SAVEIFS

exit 0



