#! /bin/bash

NAUTILUS_SCRIPT_SELECTED_FILE_PATHS=$(echo $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS | tr -d '\n')


/home/vid/roms/snes/Hacks/floating131/flips-linux "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS"


