
ARDUINO_DIR  = %{ArduinoPath}

TARGET       = %{ProjectName}
ARDUINO_LIBS = %{ArduinoLibs}

BOARD_TAG    = %{ArduinoBoard}
MCU	     = %{Mcu}
ARDUINO_PORT = %{Port}

ARDMK_DIR = %{ProjectDirectory}


include $(ARDUINO_DIR)/Arduino.mk

