#! /bin/bash


while getopts m: option
do
    case "${option}"
    in
            m) MASSAGE=${OPTARG};;
    esac
done    

BRANCH=$(git symbolic-ref --short HEAD)

make clean
make
if [ $? == 0 ]; then
    line=$(awk 'NR==3' src/version.h)
    version=$(echo $line | awk -F'"' '{print $2}')
    echo $version
    
    #git commit -a -m "$version" -m "$MASSAGE"
    
    sudo make run
    ffg build/firmware.bin firmware.hex
fi


    



